name: Deploy Screeps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Generate screeps.json from GitHub Secrets
        run: |
          echo "{\"main\": {\"token\": \"${{ secrets.SCREEPS_TOKEN }}\", \"branch\": \"main\", \"ptr\": false}}" > screeps.json

      - name: Verify screeps.json content
        run: |
          cat screeps.json
        # This step will print the contents of screeps.json to the log to verify if it's generated correctly.


      - name: Build
        run: npm run build

      - name: Set DEST environment variable
        run: echo "DEST=main" >> $GITHUB_ENV

      - name: Push to Screeps
        run: npm run push-main
