name: Deploy Screeps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to Screeps
        run: npm run push-main
        env:
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
